// ─── Careers Master Data ──────────────────────────────────────────────────────
// All 80+ careers across 8 clusters.
// w: bucket affinities [stem, creative, social, business] 0-3

export type CareerCluster =
  | 'STEM'
  | 'Business'
  | 'Creative'
  | 'Social'
  | 'Healthcare'
  | 'Law'
  | 'Science'
  | 'Hybrid';

export interface Career {
  id: string;
  title: string;
  field: string;
  cluster: CareerCluster;
  salary: string;
  growth: string;
  education: string;
  description: string;
  skills: string[];
  // Bucket affinities for fit scoring [stem, creative, social, business]
  w: [number, number, number, number];
}

export const careers: Career[] = [

  // ── STEM / Tech ──────────────────────────────────────────────────────────────
  { id: 'software-engineer',    title: 'Software Engineer',          field: 'Technology',       cluster: 'STEM',       salary: '$110k – $185k', growth: '+25% by 2032', education: "Bachelor's in CS",          description: 'Design, build, and maintain software systems and applications that power the modern world.',                       skills: ['Coding', 'Problem Solving', 'Algorithms', 'Teamwork'],                  w: [3, 1, 0, 1] },
  { id: 'computer-scientist',   title: 'Computer Scientist',         field: 'Technology',       cluster: 'STEM',       salary: '$120k – $200k', growth: '+22% by 2032', education: "PhD or Master's in CS",     description: 'Advance the theoretical foundations of computing — algorithms, AI, cryptography, and systems.',                    skills: ['Mathematics', 'Research', 'Algorithms', 'Logic'],                       w: [3, 0, 0, 1] },
  { id: 'data-scientist',       title: 'Data Scientist',             field: 'Analytics',        cluster: 'STEM',       salary: '$105k – $175k', growth: '+35% by 2032', education: "Bachelor's in CS/Stats",    description: 'Extract insights from massive datasets to drive decisions at the world\'s most data-driven companies.',            skills: ['Statistics', 'Python', 'Machine Learning', 'Visualization'],            w: [3, 1, 0, 2] },
  { id: 'data-analyst',         title: 'Data Analyst',               field: 'Analytics',        cluster: 'STEM',       salary: '$65k – $110k',  growth: '+23% by 2032', education: "Bachelor's in any field",   description: 'Turn raw data into clear business insights using SQL, Excel, and visualization tools.',                            skills: ['SQL', 'Excel', 'Statistics', 'Communication'],                          w: [2, 1, 1, 2] },
  { id: 'ai-ml-engineer',       title: 'AI / ML Engineer',           field: 'Artificial Intel.', cluster: 'STEM',      salary: '$130k – $220k', growth: '+40% by 2032', education: "Master's in CS/AI",         description: 'Build the intelligent systems behind self-driving cars, recommendation engines, and language models.',             skills: ['Python', 'Deep Learning', 'Mathematics', 'Research'],                   w: [3, 1, 0, 1] },
  { id: 'cybersecurity',        title: 'Cybersecurity Analyst',      field: 'Security',         cluster: 'STEM',       salary: '$90k – $155k',  growth: '+32% by 2032', education: "Bachelor's in CS/Security", description: 'Protect organizations from hackers, data breaches, and cyber threats in an increasingly digital world.',          skills: ['Networking', 'Ethical Hacking', 'Risk Analysis', 'Problem Solving'],    w: [3, 0, 1, 1] },
  { id: 'web-developer',        title: 'Web Developer',              field: 'Technology',       cluster: 'STEM',       salary: '$70k – $130k',  growth: '+16% by 2032', education: "Bachelor's or Bootcamp",    description: 'Build the websites and web apps that billions of people use every day.',                                           skills: ['HTML/CSS', 'JavaScript', 'React', 'Problem Solving'],                   w: [2, 2, 0, 1] },
  { id: 'app-developer',        title: 'App Developer',              field: 'Technology',       cluster: 'STEM',       salary: '$90k – $160k',  growth: '+22% by 2032', education: "Bachelor's in CS",          description: 'Create mobile apps for iOS and Android that reach millions of users worldwide.',                                  skills: ['Swift', 'Kotlin', 'UI Design', 'Problem Solving'],                      w: [3, 2, 0, 1] },
  { id: 'game-developer',       title: 'Game Developer',             field: 'Gaming',           cluster: 'STEM',       salary: '$75k – $140k',  growth: '+14% by 2032', education: "Bachelor's in CS/Game Design", description: 'Design and build video games — combining programming, art, and storytelling.',                                  skills: ['C++', 'Unity', 'Game Design', 'Creativity'],                            w: [2, 3, 0, 1] },
  { id: 'electrical-engineer',  title: 'Electrical Engineer',        field: 'Engineering',      cluster: 'STEM',       salary: '$85k – $145k',  growth: '+7% by 2032',  education: "Bachelor's in EE",          description: 'Design electrical systems, circuits, and devices — from microchips to power grids.',                              skills: ['Circuit Design', 'Mathematics', 'CAD', 'Problem Solving'],              w: [3, 1, 0, 0] },
  { id: 'mechanical-engineer',  title: 'Mechanical Engineer',        field: 'Engineering',      cluster: 'STEM',       salary: '$80k – $140k',  growth: '+10% by 2032', education: "Bachelor's in ME",          description: 'Design and build mechanical systems — engines, machines, robots, and manufacturing equipment.',                   skills: ['CAD', 'Physics', 'Mathematics', 'Problem Solving'],                     w: [3, 1, 0, 0] },
  { id: 'civil-engineer',       title: 'Civil Engineer',             field: 'Engineering',      cluster: 'STEM',       salary: '$75k – $130k',  growth: '+7% by 2032',  education: "Bachelor's in CE",          description: 'Design and oversee construction of infrastructure — bridges, roads, buildings, and water systems.',               skills: ['CAD', 'Mathematics', 'Project Management', 'Physics'],                  w: [3, 1, 1, 1] },
  { id: 'aerospace-engineer',   title: 'Aerospace Engineer',         field: 'Engineering',      cluster: 'STEM',       salary: '$95k – $165k',  growth: '+6% by 2032',  education: "Bachelor's in AE",          description: 'Design aircraft, spacecraft, and propulsion systems — from commercial jets to Mars rockets.',                     skills: ['Physics', 'Mathematics', 'CAD', 'Systems Thinking'],                    w: [3, 1, 0, 0] },
  { id: 'biomedical-engineer',  title: 'Biomedical Engineer',        field: 'Engineering',      cluster: 'STEM',       salary: '$85k – $150k',  growth: '+10% by 2032', education: "Bachelor's in BME",         description: 'Develop medical devices, prosthetics, and diagnostic equipment that save and improve lives.',                     skills: ['Biology', 'Engineering', 'Research', 'Problem Solving'],                w: [3, 1, 1, 0] },
  { id: 'chemical-engineer',    title: 'Chemical Engineer',          field: 'Engineering',      cluster: 'STEM',       salary: '$90k – $155k',  growth: '+8% by 2032',  education: "Bachelor's in ChE",         description: 'Apply chemistry and physics to design processes for manufacturing chemicals, fuels, and pharmaceuticals.',        skills: ['Chemistry', 'Mathematics', 'Process Design', 'Safety'],                 w: [3, 0, 0, 1] },
  { id: 'robotics-engineer',    title: 'Robotics Engineer',          field: 'Robotics',         cluster: 'STEM',       salary: '$95k – $165k',  growth: '+15% by 2032', education: "Bachelor's in ME/CS",       description: 'Build autonomous robots and intelligent machines for manufacturing, healthcare, and exploration.',                skills: ['Programming', 'Mechanical Design', 'AI', 'Electronics'],                w: [3, 1, 0, 0] },
  { id: 'it-specialist',        title: 'IT Specialist',              field: 'Technology',       cluster: 'STEM',       salary: '$55k – $95k',   growth: '+9% by 2032',  education: "Bachelor's or Certifications", description: 'Manage and support the technology infrastructure that keeps organizations running.',                             skills: ['Networking', 'Troubleshooting', 'Communication', 'Systems'],            w: [2, 0, 1, 1] },
  { id: 'systems-engineer',     title: 'Systems Engineer',           field: 'Engineering',      cluster: 'STEM',       salary: '$90k – $155k',  growth: '+9% by 2032',  education: "Bachelor's in SE/CS",       description: 'Design and manage complex integrated systems — from software architecture to large-scale infrastructure.',        skills: ['Systems Thinking', 'Programming', 'Project Management', 'Analysis'],    w: [3, 0, 1, 1] },
  { id: 'env-engineer',         title: 'Environmental Engineer',     field: 'Engineering',      cluster: 'STEM',       salary: '$75k – $130k',  growth: '+8% by 2032',  education: "Bachelor's in EnvE",        description: 'Develop solutions to environmental problems — clean water, air quality, waste management, and sustainability.',   skills: ['Chemistry', 'Biology', 'Problem Solving', 'Regulation'],                w: [3, 1, 2, 0] },

  // ── Business ─────────────────────────────────────────────────────────────────
  { id: 'entrepreneur',         title: 'Entrepreneur / Founder',     field: 'Business',         cluster: 'Business',   salary: 'Varies widely',  growth: 'Always in demand', education: 'Any degree + drive',      description: 'Build a company from scratch — identify a problem, create a solution, and grow a team around it.',               skills: ['Leadership', 'Risk-Taking', 'Sales', 'Resilience'],                     w: [1, 2, 1, 3] },
  { id: 'investment-banker',    title: 'Investment Banker',          field: 'Finance',          cluster: 'Business',   salary: '$100k – $250k+', growth: '+7% by 2032',  education: "Bachelor's in Finance/Econ", description: 'Advise companies on mergers, acquisitions, and capital raising — one of the highest-paying careers out of college.', skills: ['Finance', 'Analysis', 'Communication', 'Excel'],                      w: [2, 0, 1, 3] },
  { id: 'financial-analyst',    title: 'Financial Analyst',          field: 'Finance',          cluster: 'Business',   salary: '$70k – $130k',  growth: '+9% by 2032',  education: "Bachelor's in Finance",     description: 'Analyze financial data to guide investment decisions and business strategy.',                                     skills: ['Excel', 'Finance', 'Statistics', 'Communication'],                      w: [2, 0, 0, 3] },
  { id: 'accountant',           title: 'Accountant / CPA',           field: 'Finance',          cluster: 'Business',   salary: '$60k – $110k',  growth: '+6% by 2032',  education: "Bachelor's in Accounting",  description: 'Manage financial records, prepare taxes, and ensure organizations stay financially compliant.',                  skills: ['Mathematics', 'Attention to Detail', 'Accounting Software', 'Ethics'],  w: [2, 0, 1, 2] },
  { id: 'marketing-manager',    title: 'Marketing Manager',          field: 'Marketing',        cluster: 'Business',   salary: '$75k – $145k',  growth: '+10% by 2032', education: "Bachelor's in Marketing",   description: 'Lead campaigns that build brands, attract customers, and drive revenue growth.',                                  skills: ['Creativity', 'Analytics', 'Communication', 'Strategy'],                w: [0, 2, 2, 3] },
  { id: 'digital-marketer',     title: 'Digital Marketer',           field: 'Marketing',        cluster: 'Business',   salary: '$55k – $100k',  growth: '+10% by 2032', education: "Bachelor's in Marketing",   description: 'Run online campaigns across SEO, social media, email, and paid ads to grow businesses digitally.',               skills: ['SEO', 'Social Media', 'Analytics', 'Copywriting'],                      w: [1, 2, 2, 3] },
  { id: 'brand-manager',        title: 'Brand Manager',              field: 'Marketing',        cluster: 'Business',   salary: '$70k – $130k',  growth: '+8% by 2032',  education: "Bachelor's in Marketing",   description: 'Shape how the world perceives a company — managing identity, messaging, and customer experience.',               skills: ['Creativity', 'Strategy', 'Communication', 'Market Research'],           w: [0, 2, 2, 3] },
  { id: 'business-analyst',     title: 'Business Analyst',           field: 'Business',         cluster: 'Business',   salary: '$70k – $120k',  growth: '+11% by 2032', education: "Bachelor's in Business",    description: 'Bridge the gap between business needs and technology solutions — analyzing processes and recommending improvements.', skills: ['Analysis', 'Communication', 'Excel', 'Problem Solving'],              w: [2, 1, 1, 3] },
  { id: 'mgmt-consultant',      title: 'Management Consultant',      field: 'Consulting',       cluster: 'Business',   salary: '$90k – $180k',  growth: '+14% by 2032', education: "Bachelor's + MBA often",    description: 'Help the world\'s top companies solve their hardest problems — strategy, operations, and transformation.',        skills: ['Analysis', 'Communication', 'Problem Solving', 'Presentation'],         w: [2, 1, 1, 3] },
  { id: 'product-manager',      title: 'Product Manager',            field: 'Tech / Business',  cluster: 'Business',   salary: '$100k – $180k', growth: '+19% by 2032', education: "Bachelor's in any field",   description: 'Own the vision, strategy, and roadmap for a product — the CEO of the product.',                                  skills: ['Strategy', 'Communication', 'Data Analysis', 'Leadership'],             w: [2, 1, 1, 3] },
  { id: 'sales-manager',        title: 'Sales Manager',              field: 'Sales',            cluster: 'Business',   salary: '$70k – $150k',  growth: '+5% by 2032',  education: "Bachelor's in Business",    description: 'Lead a sales team to hit revenue targets — coaching reps, managing pipelines, and closing deals.',               skills: ['Leadership', 'Communication', 'Persuasion', 'CRM'],                     w: [0, 1, 2, 3] },
  { id: 'supply-chain',         title: 'Supply Chain Manager',       field: 'Operations',       cluster: 'Business',   salary: '$75k – $135k',  growth: '+28% by 2032', education: "Bachelor's in Business",    description: 'Optimize the flow of goods from manufacturer to customer — logistics, procurement, and operations.',             skills: ['Logistics', 'Analysis', 'Negotiation', 'Systems Thinking'],             w: [2, 0, 1, 3] },
  { id: 'real-estate',          title: 'Real Estate Agent / Broker', field: 'Real Estate',      cluster: 'Business',   salary: '$50k – $200k+', growth: '+5% by 2032',  education: 'License + any degree',      description: 'Help clients buy, sell, and invest in property — one of the most entrepreneurial careers available.',            skills: ['Sales', 'Communication', 'Negotiation', 'Market Knowledge'],            w: [0, 1, 2, 3] },
  { id: 'economist',            title: 'Economist',                  field: 'Economics',        cluster: 'Business',   salary: '$90k – $160k',  growth: '+6% by 2032',  education: "Master's or PhD in Econ",   description: 'Study how markets, governments, and people allocate resources — advising policy and business strategy.',          skills: ['Statistics', 'Research', 'Mathematics', 'Writing'],                     w: [3, 0, 1, 2] },

  // ── Creative / Media ─────────────────────────────────────────────────────────
  { id: 'graphic-designer',     title: 'Graphic Designer',           field: 'Design',           cluster: 'Creative',   salary: '$50k – $90k',   growth: '+3% by 2032',  education: "Bachelor's in Design",      description: 'Create visual identities, marketing materials, and digital assets that communicate ideas powerfully.',           skills: ['Adobe Suite', 'Typography', 'Color Theory', 'Creativity'],              w: [0, 3, 1, 1] },
  { id: 'ux-designer',          title: 'UX / UI Designer',           field: 'Design',           cluster: 'Creative',   salary: '$80k – $145k',  growth: '+16% by 2032', education: "Bachelor's in Design/HCI",  description: 'Design digital products that are intuitive, beautiful, and delightful to use — the bridge between tech and people.', skills: ['Figma', 'User Research', 'Prototyping', 'Empathy'],                   w: [1, 3, 2, 1] },
  { id: 'product-designer',     title: 'Product Designer',           field: 'Design',           cluster: 'Creative',   salary: '$90k – $160k',  growth: '+16% by 2032', education: "Bachelor's in Design",      description: 'Shape the look, feel, and function of physical and digital products from concept to launch.',                    skills: ['Figma', 'Prototyping', 'Systems Thinking', 'User Research'],            w: [2, 3, 1, 1] },
  { id: 'animator',             title: 'Animator',                   field: 'Animation',        cluster: 'Creative',   salary: '$55k – $100k',  growth: '+5% by 2032',  education: "Bachelor's in Animation",   description: 'Bring characters and stories to life through 2D/3D animation for film, TV, games, and advertising.',            skills: ['Maya', 'After Effects', 'Drawing', 'Storytelling'],                     w: [1, 3, 1, 0] },
  { id: 'film-director',        title: 'Film Director',              field: 'Film',             cluster: 'Creative',   salary: '$60k – $200k+', growth: '+8% by 2032',  education: "Bachelor's in Film",        description: 'Lead the creative vision of a film or TV production — from script to screen.',                                   skills: ['Storytelling', 'Leadership', 'Visual Thinking', 'Communication'],       w: [0, 3, 2, 1] },
  { id: 'video-editor',         title: 'Video Editor',               field: 'Film',             cluster: 'Creative',   salary: '$50k – $95k',   growth: '+7% by 2032',  education: "Bachelor's in Film/Media",  description: 'Shape raw footage into compelling stories for film, TV, YouTube, and social media.',                             skills: ['Premiere Pro', 'After Effects', 'Storytelling', 'Attention to Detail'], w: [1, 3, 1, 0] },
  { id: 'photographer',         title: 'Photographer',               field: 'Photography',      cluster: 'Creative',   salary: '$40k – $85k',   growth: '+4% by 2032',  education: 'Portfolio + any degree',    description: 'Capture moments, products, and stories through the lens — for editorial, commercial, or fine art.',             skills: ['Composition', 'Lighting', 'Photoshop', 'Creativity'],                   w: [0, 3, 1, 1] },
  { id: 'content-creator',      title: 'Content Creator',            field: 'Media',            cluster: 'Creative',   salary: '$40k – $200k+', growth: 'Rapidly growing', education: 'Any degree + portfolio',  description: 'Build an audience on YouTube, TikTok, or Instagram by creating engaging content around your passion.',          skills: ['Video Production', 'Editing', 'Social Media', 'Storytelling'],          w: [0, 3, 2, 2] },
  { id: 'social-media-mgr',     title: 'Social Media Manager',       field: 'Marketing',        cluster: 'Creative',   salary: '$50k – $90k',   growth: '+10% by 2032', education: "Bachelor's in Marketing",   description: 'Manage a brand\'s presence on social platforms — creating content, growing audiences, and driving engagement.',  skills: ['Content Creation', 'Analytics', 'Copywriting', 'Strategy'],             w: [0, 2, 2, 2] },
  { id: 'journalist',           title: 'Journalist',                 field: 'Media',            cluster: 'Creative',   salary: '$45k – $90k',   growth: '-4% by 2032',  education: "Bachelor's in Journalism",  description: 'Investigate and report on the stories that matter — in print, digital, broadcast, or podcast.',                 skills: ['Writing', 'Research', 'Interviewing', 'Critical Thinking'],             w: [0, 2, 3, 1] },
  { id: 'writer-author',        title: 'Writer / Author',            field: 'Writing',          cluster: 'Creative',   salary: '$45k – $120k',  growth: '+4% by 2032',  education: "Bachelor's in English",     description: 'Craft books, scripts, articles, or copy that informs, entertains, and moves people.',                           skills: ['Writing', 'Research', 'Creativity', 'Discipline'],                      w: [0, 3, 2, 1] },
  { id: 'copywriter',           title: 'Copywriter',                 field: 'Marketing',        cluster: 'Creative',   salary: '$55k – $110k',  growth: '+7% by 2032',  education: "Bachelor's in English",     description: 'Write the words that sell — ads, websites, emails, and campaigns that drive action.',                           skills: ['Writing', 'Persuasion', 'Creativity', 'Marketing'],                     w: [0, 3, 1, 2] },
  { id: 'music-producer',       title: 'Music Producer',             field: 'Music',            cluster: 'Creative',   salary: '$45k – $150k+', growth: '+5% by 2032',  education: 'Portfolio + any degree',    description: 'Create, arrange, and produce music for artists, films, ads, and games.',                                         skills: ['Music Theory', 'DAW Software', 'Creativity', 'Collaboration'],          w: [0, 3, 1, 1] },
  { id: 'game-designer',        title: 'Game Designer',              field: 'Gaming',           cluster: 'Creative',   salary: '$65k – $120k',  growth: '+14% by 2032', education: "Bachelor's in Game Design", description: 'Design the rules, mechanics, levels, and experiences that make games compelling and fun.',                      skills: ['Game Engines', 'Storytelling', 'Design Thinking', 'Programming'],       w: [2, 3, 1, 1] },
  { id: 'fashion-designer',     title: 'Fashion Designer',           field: 'Fashion',          cluster: 'Creative',   salary: '$50k – $120k',  growth: '+3% by 2032',  education: "Bachelor's in Fashion",     description: 'Create clothing, accessories, and collections that define culture and personal expression.',                     skills: ['Sketching', 'Sewing', 'Trend Forecasting', 'Creativity'],               w: [0, 3, 1, 1] },
  { id: 'architect-creative',   title: 'Architect',                  field: 'Architecture',     cluster: 'Creative',   salary: '$75k – $140k',  growth: '+5% by 2032',  education: "Bachelor's + Master's in Arch", description: 'Design buildings and spaces that shape how people live, work, and experience the world.',                    skills: ['CAD', 'Design Thinking', 'Mathematics', 'Creativity'],                  w: [2, 3, 1, 1] },

  // ── Social / People ──────────────────────────────────────────────────────────
  { id: 'psychologist',         title: 'Psychologist',               field: 'Psychology',       cluster: 'Social',     salary: '$80k – $140k',  growth: '+6% by 2032',  education: "Doctoral degree (PhD/PsyD)", description: 'Study human behavior and help people overcome mental health challenges through therapy and research.',           skills: ['Empathy', 'Research', 'Communication', 'Critical Thinking'],            w: [1, 1, 3, 0] },
  { id: 'therapist',            title: 'Therapist / Counselor',      field: 'Mental Health',    cluster: 'Social',     salary: '$55k – $100k',  growth: '+22% by 2032', education: "Master's in Counseling",    description: 'Provide mental health support to individuals, couples, and families navigating life\'s challenges.',            skills: ['Empathy', 'Active Listening', 'Communication', 'Patience'],             w: [0, 1, 3, 0] },
  { id: 'teacher',              title: 'Teacher / Professor',        field: 'Education',        cluster: 'Social',     salary: '$45k – $90k',   growth: '+5% by 2032',  education: "Bachelor's + Teaching Cert", description: 'Shape the next generation — inspiring curiosity, building skills, and changing lives in the classroom.',       skills: ['Communication', 'Patience', 'Subject Expertise', 'Creativity'],         w: [1, 1, 3, 0] },
  { id: 'social-worker',        title: 'Social Worker',              field: 'Human Services',   cluster: 'Social',     salary: '$45k – $80k',   growth: '+9% by 2032',  education: "Bachelor's in Social Work", description: 'Advocate for vulnerable populations — children, families, and communities facing hardship.',                  skills: ['Empathy', 'Advocacy', 'Communication', 'Problem Solving'],              w: [0, 1, 3, 0] },
  { id: 'hr-manager',           title: 'Human Resources Manager',    field: 'HR',               cluster: 'Social',     salary: '$70k – $130k',  growth: '+7% by 2032',  education: "Bachelor's in HR/Business", description: 'Attract, develop, and retain the talent that makes organizations thrive.',                                      skills: ['Communication', 'Empathy', 'Organization', 'Conflict Resolution'],      w: [0, 1, 3, 2] },
  { id: 'lawyer',               title: 'Lawyer',                     field: 'Law',              cluster: 'Social',     salary: '$80k – $200k+', growth: '+10% by 2032', education: 'JD (Law Degree)',            description: 'Advocate for clients in court, draft contracts, and navigate the legal system across every sector of society.',  skills: ['Research', 'Writing', 'Argumentation', 'Critical Thinking'],            w: [1, 1, 3, 2] },
  { id: 'paralegal',            title: 'Paralegal',                  field: 'Law',              cluster: 'Social',     salary: '$45k – $80k',   growth: '+14% by 2032', education: "Bachelor's + Certificate",  description: 'Support attorneys with legal research, document preparation, and case management.',                             skills: ['Research', 'Writing', 'Organization', 'Attention to Detail'],           w: [1, 1, 2, 1] },
  { id: 'political-scientist',  title: 'Political Scientist',        field: 'Government',       cluster: 'Social',     salary: '$70k – $130k',  growth: '+6% by 2032',  education: "Master's or PhD in PolSci", description: 'Study political systems, public policy, and international relations to understand how power shapes the world.',  skills: ['Research', 'Writing', 'Analysis', 'Critical Thinking'],                 w: [1, 1, 3, 1] },
  { id: 'diplomat',             title: 'Diplomat / Foreign Service', field: 'Government',       cluster: 'Social',     salary: '$55k – $120k',  growth: '+6% by 2032',  education: "Bachelor's + Foreign Service Exam", description: 'Represent your country abroad — negotiating treaties, building alliances, and advancing national interests.',  skills: ['Languages', 'Communication', 'Cultural Awareness', 'Negotiation'],     w: [0, 1, 3, 2] },
  { id: 'pr-specialist',        title: 'Public Relations Specialist',field: 'Communications',   cluster: 'Social',     salary: '$55k – $100k',  growth: '+8% by 2032',  education: "Bachelor's in PR/Comm",     description: 'Shape public perception of organizations and individuals through strategic communications and media relations.',  skills: ['Writing', 'Communication', 'Strategy', 'Media Relations'],              w: [0, 2, 3, 2] },
  { id: 'speech-therapist',     title: 'Speech Therapist',           field: 'Healthcare',       cluster: 'Social',     salary: '$70k – $110k',  growth: '+19% by 2032', education: "Master's in SLP",           description: 'Help people of all ages overcome speech, language, and communication disorders.',                               skills: ['Empathy', 'Communication', 'Patience', 'Clinical Skills'],              w: [0, 1, 3, 0] },
  { id: 'school-counselor',     title: 'School Counselor',           field: 'Education',        cluster: 'Social',     salary: '$55k – $90k',   growth: '+10% by 2032', education: "Master's in Counseling",    description: 'Guide students through academic, social, and career challenges — making a lasting impact on young lives.',      skills: ['Empathy', 'Communication', 'Organization', 'Advocacy'],                 w: [0, 1, 3, 0] },
  { id: 'nonprofit-director',   title: 'Nonprofit Director',         field: 'Nonprofit',        cluster: 'Social',     salary: '$55k – $110k',  growth: '+9% by 2032',  education: "Bachelor's + Experience",   description: 'Lead an organization dedicated to a cause — managing teams, fundraising, and driving social impact.',           skills: ['Leadership', 'Fundraising', 'Communication', 'Strategy'],               w: [0, 1, 3, 2] },

  // ── Healthcare / Medical ──────────────────────────────────────────────────────
  { id: 'doctor',               title: 'Doctor (Physician)',          field: 'Medicine',         cluster: 'Healthcare', salary: '$200k – $400k+', growth: '+3% by 2032',  education: 'MD (Medical Degree)',        description: 'Diagnose and treat illness, injury, and disease — one of the most respected and impactful careers.',            skills: ['Biology', 'Empathy', 'Critical Thinking', 'Communication'],             w: [3, 0, 2, 0] },
  { id: 'surgeon',              title: 'Surgeon',                    field: 'Medicine',         cluster: 'Healthcare', salary: '$300k – $600k+', growth: '+3% by 2032',  education: 'MD + Surgical Residency',    description: 'Perform life-saving operations — one of the most demanding and rewarding careers in medicine.',                 skills: ['Precision', 'Biology', 'Stamina', 'Decision-Making'],                   w: [3, 1, 1, 0] },
  { id: 'nurse',                title: 'Nurse (RN / NP)',            field: 'Nursing',          cluster: 'Healthcare', salary: '$70k – $130k',  growth: '+6% by 2032',  education: "Bachelor's in Nursing",     description: 'Provide direct patient care, administer treatments, and serve as the backbone of the healthcare system.',       skills: ['Empathy', 'Clinical Skills', 'Communication', 'Stamina'],               w: [2, 0, 3, 0] },
  { id: 'dentist',              title: 'Dentist',                    field: 'Dentistry',        cluster: 'Healthcare', salary: '$150k – $250k', growth: '+4% by 2032',  education: 'DDS or DMD',                 description: 'Diagnose and treat oral health conditions — one of the most stable and well-compensated healthcare careers.',   skills: ['Precision', 'Biology', 'Communication', 'Business'],                    w: [2, 1, 2, 1] },
  { id: 'pharmacist',           title: 'Pharmacist',                 field: 'Pharmacy',         cluster: 'Healthcare', salary: '$120k – $160k', growth: '+2% by 2032',  education: 'PharmD',                     description: 'Dispense medications, counsel patients, and ensure safe drug use across hospitals and pharmacies.',             skills: ['Chemistry', 'Attention to Detail', 'Communication', 'Biology'],         w: [3, 0, 2, 0] },
  { id: 'physical-therapist',   title: 'Physical Therapist',         field: 'Rehabilitation',   cluster: 'Healthcare', salary: '$80k – $120k',  growth: '+17% by 2032', education: 'DPT (Doctoral)',             description: 'Help patients recover from injuries and surgeries through targeted exercise and rehabilitation programs.',       skills: ['Anatomy', 'Empathy', 'Communication', 'Problem Solving'],               w: [2, 1, 3, 0] },
  { id: 'occupational-therapist',title: 'Occupational Therapist',   field: 'Rehabilitation',   cluster: 'Healthcare', salary: '$75k – $115k',  growth: '+12% by 2032', education: "Master's in OT",            description: 'Help people with disabilities or injuries regain independence in daily activities.',                            skills: ['Empathy', 'Creativity', 'Communication', 'Problem Solving'],            w: [1, 2, 3, 0] },
  { id: 'veterinarian',         title: 'Veterinarian',               field: 'Veterinary',       cluster: 'Healthcare', salary: '$90k – $160k',  growth: '+19% by 2032', education: 'DVM',                        description: 'Diagnose and treat animals — from household pets to livestock to exotic wildlife.',                             skills: ['Biology', 'Empathy', 'Problem Solving', 'Communication'],               w: [3, 0, 2, 0] },
  { id: 'public-health',        title: 'Public Health Specialist',   field: 'Public Health',    cluster: 'Healthcare', salary: '$55k – $100k',  growth: '+13% by 2032', education: "Bachelor's/Master's in PH", description: 'Protect and improve community health through policy, research, and education at the population level.',        skills: ['Research', 'Communication', 'Data Analysis', 'Advocacy'],               w: [2, 0, 3, 1] },
  { id: 'nutritionist',         title: 'Nutritionist / Dietitian',   field: 'Nutrition',        cluster: 'Healthcare', salary: '$55k – $85k',   growth: '+7% by 2032',  education: "Bachelor's in Nutrition",   description: 'Help individuals and communities improve health through evidence-based dietary guidance.',                       skills: ['Biology', 'Communication', 'Empathy', 'Research'],                      w: [2, 0, 3, 0] },
  { id: 'medical-researcher',   title: 'Medical Researcher',         field: 'Research',         cluster: 'Healthcare', salary: '$70k – $130k',  growth: '+10% by 2032', education: "PhD in Biomedical Science",  description: 'Conduct clinical and laboratory research to develop new treatments, drugs, and medical breakthroughs.',         skills: ['Biology', 'Research', 'Statistics', 'Critical Thinking'],               w: [3, 0, 1, 0] },

  // ── Law / Government ─────────────────────────────────────────────────────────
  { id: 'judge',                title: 'Judge',                      field: 'Law',              cluster: 'Law',        salary: '$100k – $220k', growth: '+4% by 2032',  education: 'JD + Experience',            description: 'Preside over legal proceedings, interpret laws, and deliver justice in courts at every level.',                skills: ['Legal Knowledge', 'Critical Thinking', 'Impartiality', 'Writing'],      w: [1, 0, 3, 1] },
  { id: 'criminal-justice',     title: 'Criminal Justice Officer',   field: 'Law Enforcement',  cluster: 'Law',        salary: '$50k – $90k',   growth: '+3% by 2032',  education: "Bachelor's in CJ",          description: 'Enforce laws, investigate crimes, and protect communities as a police officer, detective, or federal agent.',   skills: ['Physical Fitness', 'Communication', 'Ethics', 'Problem Solving'],       w: [1, 0, 3, 1] },
  { id: 'policy-analyst',       title: 'Policy Analyst',             field: 'Government',       cluster: 'Law',        salary: '$60k – $110k',  growth: '+6% by 2032',  education: "Master's in Public Policy", description: 'Research and evaluate government policies to recommend evidence-based solutions to public problems.',           skills: ['Research', 'Writing', 'Analysis', 'Communication'],                     w: [2, 1, 3, 1] },
  { id: 'public-admin',         title: 'Public Administrator',       field: 'Government',       cluster: 'Law',        salary: '$55k – $100k',  growth: '+6% by 2032',  education: "Master's in Public Admin",  description: 'Manage government agencies and public programs — ensuring services reach the people who need them.',           skills: ['Organization', 'Leadership', 'Communication', 'Budget Management'],     w: [1, 0, 3, 2] },

  // ── Science / Research ────────────────────────────────────────────────────────
  { id: 'research-scientist',   title: 'Research Scientist',         field: 'Research',         cluster: 'Science',    salary: '$75k – $140k',  growth: '+8% by 2032',  education: 'PhD in relevant field',     description: 'Push the boundaries of human knowledge through rigorous experimentation and discovery.',                        skills: ['Research', 'Statistics', 'Writing', 'Critical Thinking'],               w: [3, 0, 1, 0] },
  { id: 'biologist',            title: 'Biologist',                  field: 'Biology',          cluster: 'Science',    salary: '$65k – $120k',  growth: '+5% by 2032',  education: "Bachelor's/PhD in Biology", description: 'Study living organisms — from microbes to ecosystems — to understand life and solve biological challenges.',    skills: ['Biology', 'Research', 'Lab Skills', 'Critical Thinking'],               w: [3, 0, 1, 0] },
  { id: 'chemist',              title: 'Chemist',                    field: 'Chemistry',        cluster: 'Science',    salary: '$70k – $130k',  growth: '+6% by 2032',  education: "Bachelor's/PhD in Chemistry", description: 'Study matter and its properties to develop new materials, medicines, and industrial processes.',              skills: ['Chemistry', 'Lab Skills', 'Mathematics', 'Research'],                   w: [3, 0, 0, 1] },
  { id: 'physicist',            title: 'Physicist',                  field: 'Physics',          cluster: 'Science',    salary: '$80k – $150k',  growth: '+8% by 2032',  education: 'PhD in Physics',             description: 'Explore the fundamental laws of the universe — from quantum mechanics to cosmology.',                          skills: ['Mathematics', 'Research', 'Critical Thinking', 'Programming'],          w: [3, 0, 0, 0] },
  { id: 'env-scientist',        title: 'Environmental Scientist',    field: 'Environment',      cluster: 'Science',    salary: '$60k – $110k',  growth: '+7% by 2032',  education: "Bachelor's in EnvSci",      description: 'Study and protect the natural environment — analyzing pollution, climate change, and ecosystem health.',        skills: ['Biology', 'Chemistry', 'Research', 'Communication'],                    w: [3, 1, 2, 0] },
  { id: 'epidemiologist',       title: 'Epidemiologist',             field: 'Public Health',    cluster: 'Science',    salary: '$70k – $120k',  growth: '+26% by 2032', education: "Master's/PhD in Epidemiology", description: 'Investigate the patterns and causes of disease in populations to prevent outbreaks and improve public health.', skills: ['Statistics', 'Research', 'Biology', 'Communication'],                  w: [3, 0, 2, 0] },

  // ── Modern / Hybrid ───────────────────────────────────────────────────────────
  { id: 'ux-researcher',        title: 'UX Researcher',              field: 'Design / Tech',    cluster: 'Hybrid',     salary: '$85k – $150k',  growth: '+16% by 2032', education: "Bachelor's in Psychology/Design", description: 'Conduct user research to understand how people think and behave — informing product and design decisions.',  skills: ['Research', 'Empathy', 'Data Analysis', 'Communication'],               w: [1, 2, 3, 1] },
  { id: 'data-engineer',        title: 'Data Engineer',              field: 'Tech / Analytics', cluster: 'Hybrid',     salary: '$110k – $180k', growth: '+35% by 2032', education: "Bachelor's in CS",          description: 'Build the data pipelines and infrastructure that power analytics, AI, and business intelligence.',             skills: ['Python', 'SQL', 'Cloud Platforms', 'Systems Design'],                   w: [3, 0, 0, 2] },
  { id: 'ai-ethics',            title: 'AI Ethics Specialist',       field: 'Tech / Policy',    cluster: 'Hybrid',     salary: '$90k – $160k',  growth: 'Emerging field', education: "Master's in CS/Philosophy", description: 'Ensure AI systems are fair, transparent, and aligned with human values — one of the most important emerging roles.', skills: ['Critical Thinking', 'Research', 'Communication', 'Philosophy'],       w: [2, 1, 3, 1] },
  { id: 'tech-entrepreneur',    title: 'Tech Entrepreneur',          field: 'Tech / Business',  cluster: 'Hybrid',     salary: 'Varies widely',  growth: 'Always growing', education: 'Any degree + execution',  description: 'Build technology companies from scratch — combining technical knowledge with business acumen and vision.',      skills: ['Leadership', 'Technical Skills', 'Sales', 'Resilience'],                w: [2, 2, 1, 3] },
  { id: 'sustainability',       title: 'Sustainability Consultant',  field: 'Environment / Biz',cluster: 'Hybrid',     salary: '$65k – $120k',  growth: '+15% by 2032', education: "Bachelor's in EnvSci/Business", description: 'Help organizations reduce their environmental impact and build sustainable business practices.',             skills: ['Research', 'Communication', 'Strategy', 'Environmental Science'],      w: [2, 1, 2, 2] },
  { id: 'hcd',                  title: 'Human-Centered Designer',    field: 'Design / Social',  cluster: 'Hybrid',     salary: '$75k – $135k',  growth: '+12% by 2032', education: "Bachelor's in Design/HCI",  description: 'Design products, services, and systems with deep empathy for the people who use them.',                        skills: ['Empathy', 'Design Thinking', 'Research', 'Prototyping'],                w: [1, 3, 3, 1] },
  { id: 'health-informatics',   title: 'Health Informatics Specialist', field: 'Health / Tech', cluster: 'Hybrid',     salary: '$75k – $130k',  growth: '+17% by 2032', education: "Bachelor's in Health Informatics", description: 'Bridge healthcare and technology — managing health data systems to improve patient outcomes.',            skills: ['Data Analysis', 'Healthcare Knowledge', 'IT', 'Communication'],         w: [3, 0, 2, 1] },
];

// ─── Fit scoring ──────────────────────────────────────────────────────────────

export function computeCareerFit(
  career: Career,
  scores: { stem: number; creative: number; social: number; business: number },
  total: number,
): number {
  const raw =
    career.w[0] * scores.stem +
    career.w[1] * scores.creative +
    career.w[2] * scores.social +
    career.w[3] * scores.business;
  const maxPossible = Math.max(...career.w) * (total || 1);
  const base = maxPossible > 0 ? Math.round((raw / maxPossible) * 100) : 50;
  return Math.min(99, Math.max(35, base));
}
