// ─── Colleges Master Data ─────────────────────────────────────────────────────
// Tier: 'ivy' | 'elite' | 'uc' | 'public' | 'safety'
// Difficulty: 'reach' | 'target' | 'safety'
// strengths: which profile clusters this school is strong for

export type CollegeTier = 'ivy' | 'elite' | 'uc' | 'public' | 'safety';
export type CollegeDifficulty = 'reach' | 'target' | 'safety';

export interface College {
  id: string;
  name: string;
  shortName: string;
  location: string;
  type: string;
  size: 'Small' | 'Medium' | 'Large';
  tier: CollegeTier;
  difficulty: CollegeDifficulty;
  category: string;                       // for filter tabs
  tuition: string;
  acceptanceRate: string;
  enrollment: string;
  topPrograms: string[];
  description: string;
  strengths: Array<'STEM' | 'Business' | 'Creative' | 'Social'>; // profile cluster fit
  tags: string[];
  // Bucket affinities for fit scoring [stem, creative, social, business] 0-3
  w: [number, number, number, number];
}

export const colleges: College[] = [

  // ── Ivy League ──────────────────────────────────────────────────────────────
  {
    id: 'harvard',
    name: 'Harvard University',
    shortName: 'Harvard',
    location: 'Cambridge, MA',
    type: 'Private Research',
    size: 'Large',
    tier: 'ivy',
    difficulty: 'reach',
    category: 'Ivy',
    tuition: '$59,076/yr',
    acceptanceRate: '3%',
    enrollment: '23,000',
    topPrograms: ['Economics', 'Computer Science', 'Political Science', 'Pre-Med', 'Law'],
    description: 'The oldest university in the US and a global symbol of academic excellence across every discipline.',
    strengths: ['STEM', 'Business', 'Social'],
    tags: ['Ivy League', 'Research', 'Highly Selective', 'Prestige'],
    w: [3, 1, 2, 3],
  },
  {
    id: 'yale',
    name: 'Yale University',
    shortName: 'Yale',
    location: 'New Haven, CT',
    type: 'Private Research',
    size: 'Large',
    tier: 'ivy',
    difficulty: 'reach',
    category: 'Ivy',
    tuition: '$62,250/yr',
    acceptanceRate: '5%',
    enrollment: '14,000',
    topPrograms: ['Political Science', 'Economics', 'History', 'Drama', 'Law'],
    description: 'Renowned for its law school, arts programs, and residential college system that fosters deep community.',
    strengths: ['Social', 'Creative', 'Business'],
    tags: ['Ivy League', 'Liberal Arts', 'Arts', 'Prestige'],
    w: [1, 3, 3, 2],
  },
  {
    id: 'princeton',
    name: 'Princeton University',
    shortName: 'Princeton',
    location: 'Princeton, NJ',
    type: 'Private Research',
    size: 'Medium',
    tier: 'ivy',
    difficulty: 'reach',
    category: 'Ivy',
    tuition: '$57,410/yr',
    acceptanceRate: '4%',
    enrollment: '10,000',
    topPrograms: ['Mathematics', 'Computer Science', 'Engineering', 'Public Policy', 'Economics'],
    description: 'A world-class research university known for its generous financial aid and intimate academic environment.',
    strengths: ['STEM', 'Social', 'Business'],
    tags: ['Ivy League', 'Research', 'STEM', 'Prestige'],
    w: [3, 1, 2, 2],
  },
  {
    id: 'columbia',
    name: 'Columbia University',
    shortName: 'Columbia',
    location: 'New York, NY',
    type: 'Private Research',
    size: 'Large',
    tier: 'ivy',
    difficulty: 'reach',
    category: 'Ivy',
    tuition: '$65,524/yr',
    acceptanceRate: '4%',
    enrollment: '35,000',
    topPrograms: ['Computer Science', 'Business', 'Journalism', 'Political Science', 'Engineering'],
    description: 'Located in the heart of New York City, Columbia offers unmatched access to industry, media, and finance.',
    strengths: ['Business', 'Social', 'STEM'],
    tags: ['Ivy League', 'NYC', 'Business', 'Journalism'],
    w: [2, 2, 2, 3],
  },
  {
    id: 'upenn',
    name: 'University of Pennsylvania',
    shortName: 'UPenn / Wharton',
    location: 'Philadelphia, PA',
    type: 'Private Research',
    size: 'Large',
    tier: 'ivy',
    difficulty: 'reach',
    category: 'Ivy',
    tuition: '$63,452/yr',
    acceptanceRate: '7%',
    enrollment: '22,000',
    topPrograms: ['Business (Wharton)', 'Finance', 'Economics', 'Computer Science', 'Nursing'],
    description: 'Home to the world-renowned Wharton School — the top undergraduate business program in the country.',
    strengths: ['Business', 'STEM'],
    tags: ['Ivy League', 'Business', 'Finance', 'Wharton'],
    w: [2, 1, 1, 3],
  },
  {
    id: 'brown',
    name: 'Brown University',
    shortName: 'Brown',
    location: 'Providence, RI',
    type: 'Private Research',
    size: 'Medium',
    tier: 'ivy',
    difficulty: 'reach',
    category: 'Ivy',
    tuition: '$65,146/yr',
    acceptanceRate: '5%',
    enrollment: '10,700',
    topPrograms: ['Computer Science', 'Biology', 'Economics', 'Public Health', 'Cognitive Science'],
    description: "Known for its Open Curriculum that lets students design their own education — perfect for independent thinkers.",
    strengths: ['STEM', 'Creative', 'Social'],
    tags: ['Ivy League', 'Open Curriculum', 'Flexible', 'Research'],
    w: [2, 2, 2, 1],
  },
  {
    id: 'dartmouth',
    name: 'Dartmouth College',
    shortName: 'Dartmouth',
    location: 'Hanover, NH',
    type: 'Private Research',
    size: 'Small',
    tier: 'ivy',
    difficulty: 'reach',
    category: 'Ivy',
    tuition: '$62,430/yr',
    acceptanceRate: '6%',
    enrollment: '6,700',
    topPrograms: ['Economics', 'Government', 'Engineering', 'Computer Science', 'Business (Tuck)'],
    description: 'A tight-knit Ivy with a strong business school (Tuck), outdoor culture, and exceptional alumni network.',
    strengths: ['Business', 'Social', 'STEM'],
    tags: ['Ivy League', 'Small Campus', 'Business', 'Community'],
    w: [2, 1, 2, 3],
  },
  {
    id: 'cornell',
    name: 'Cornell University',
    shortName: 'Cornell',
    location: 'Ithaca, NY',
    type: 'Private Research',
    size: 'Large',
    tier: 'ivy',
    difficulty: 'reach',
    category: 'Ivy',
    tuition: '$63,200/yr',
    acceptanceRate: '11%',
    enrollment: '25,000',
    topPrograms: ['Engineering', 'Computer Science', 'Hotel Administration', 'Agriculture', 'Architecture'],
    description: 'The most accessible Ivy with the broadest range of programs — from engineering to hospitality to agriculture.',
    strengths: ['STEM', 'Business', 'Creative'],
    tags: ['Ivy League', 'Engineering', 'Diverse Programs', 'Research'],
    w: [3, 1, 1, 2],
  },

  // ── Elite Private Universities ───────────────────────────────────────────────
  {
    id: 'mit',
    name: 'Massachusetts Institute of Technology',
    shortName: 'MIT',
    location: 'Cambridge, MA',
    type: 'Private Research',
    size: 'Medium',
    tier: 'elite',
    difficulty: 'reach',
    category: 'Elite',
    tuition: '$57,986/yr',
    acceptanceRate: '4%',
    enrollment: '11,500',
    topPrograms: ['Computer Science', 'Engineering', 'Mathematics', 'Physics', 'AI / Robotics'],
    description: "The world's leading science and technology university — if you want to build the future, this is ground zero.",
    strengths: ['STEM'],
    tags: ['STEM', 'Research', 'Highly Selective', 'Tech'],
    w: [3, 1, 0, 1],
  },
  {
    id: 'stanford',
    name: 'Stanford University',
    shortName: 'Stanford',
    location: 'Stanford, CA',
    type: 'Private Research',
    size: 'Large',
    tier: 'elite',
    difficulty: 'reach',
    category: 'Elite',
    tuition: '$56,169/yr',
    acceptanceRate: '4%',
    enrollment: '17,000',
    topPrograms: ['Computer Science', 'Business', 'Engineering', 'Medicine', 'Design'],
    description: 'At the heart of Silicon Valley — the birthplace of Google, Netflix, and hundreds of startups.',
    strengths: ['STEM', 'Business', 'Creative'],
    tags: ['STEM', 'Business', 'Highly Selective', 'Silicon Valley'],
    w: [3, 2, 1, 3],
  },
  {
    id: 'caltech',
    name: 'California Institute of Technology',
    shortName: 'Caltech',
    location: 'Pasadena, CA',
    type: 'Private Research',
    size: 'Small',
    tier: 'elite',
    difficulty: 'reach',
    category: 'Elite',
    tuition: '$60,816/yr',
    acceptanceRate: '4%',
    enrollment: '2,400',
    topPrograms: ['Physics', 'Engineering', 'Computer Science', 'Chemistry', 'Astronomy'],
    description: 'The most science-intensive university in the world — small, elite, and laser-focused on STEM research.',
    strengths: ['STEM'],
    tags: ['STEM', 'Research', 'Science', 'Highly Selective'],
    w: [3, 0, 0, 0],
  },
  {
    id: 'northwestern',
    name: 'Northwestern University',
    shortName: 'Northwestern',
    location: 'Evanston, IL',
    type: 'Private Research',
    size: 'Large',
    tier: 'elite',
    difficulty: 'reach',
    category: 'Elite',
    tuition: '$63,468/yr',
    acceptanceRate: '7%',
    enrollment: '22,000',
    topPrograms: ['Journalism', 'Engineering', 'Business (Kellogg)', 'Theatre', 'Computer Science'],
    description: 'A top-10 university blending elite research with outstanding journalism, theatre, and business programs.',
    strengths: ['Creative', 'Business', 'STEM'],
    tags: ['Research', 'Journalism', 'Business', 'Arts'],
    w: [2, 3, 2, 3],
  },
  {
    id: 'duke',
    name: 'Duke University',
    shortName: 'Duke',
    location: 'Durham, NC',
    type: 'Private Research',
    size: 'Large',
    tier: 'elite',
    difficulty: 'reach',
    category: 'Elite',
    tuition: '$62,688/yr',
    acceptanceRate: '6%',
    enrollment: '17,000',
    topPrograms: ['Pre-Med', 'Public Policy', 'Computer Science', 'Economics', 'Engineering'],
    description: 'A powerhouse in medicine, public policy, and research — with one of the best campus cultures in the country.',
    strengths: ['STEM', 'Social', 'Business'],
    tags: ['Research', 'Pre-Med', 'Public Policy', 'Selective'],
    w: [3, 1, 2, 2],
  },
  {
    id: 'johns-hopkins',
    name: 'Johns Hopkins University',
    shortName: 'Johns Hopkins',
    location: 'Baltimore, MD',
    type: 'Private Research',
    size: 'Large',
    tier: 'elite',
    difficulty: 'reach',
    category: 'Elite',
    tuition: '$60,480/yr',
    acceptanceRate: '7%',
    enrollment: '27,000',
    topPrograms: ['Pre-Med', 'Public Health', 'Biomedical Engineering', 'International Studies', 'Computer Science'],
    description: 'The #1 university for research funding — the gold standard for pre-med, public health, and biomedical fields.',
    strengths: ['STEM', 'Social'],
    tags: ['Research', 'Pre-Med', 'Public Health', 'Biomedical'],
    w: [3, 0, 2, 1],
  },
  {
    id: 'uchicago',
    name: 'University of Chicago',
    shortName: 'UChicago',
    location: 'Chicago, IL',
    type: 'Private Research',
    size: 'Large',
    tier: 'elite',
    difficulty: 'reach',
    category: 'Elite',
    tuition: '$63,801/yr',
    acceptanceRate: '6%',
    enrollment: '18,000',
    topPrograms: ['Economics', 'Mathematics', 'Political Science', 'Philosophy', 'Statistics'],
    description: 'The intellectual capital of the US — rigorous, analytical, and home to more Nobel laureates than most countries.',
    strengths: ['STEM', 'Business', 'Social'],
    tags: ['Research', 'Economics', 'Analytical', 'Rigorous'],
    w: [3, 1, 2, 3],
  },
  {
    id: 'vanderbilt',
    name: 'Vanderbilt University',
    shortName: 'Vanderbilt',
    location: 'Nashville, TN',
    type: 'Private Research',
    size: 'Large',
    tier: 'elite',
    difficulty: 'reach',
    category: 'Elite',
    tuition: '$60,348/yr',
    acceptanceRate: '7%',
    enrollment: '13,500',
    topPrograms: ['Pre-Med', 'Education', 'Engineering', 'Business (Owen)', 'Music'],
    description: 'A top-15 university with exceptional pre-med, education, and music programs in a vibrant Southern city.',
    strengths: ['STEM', 'Social', 'Creative'],
    tags: ['Research', 'Pre-Med', 'Education', 'Music'],
    w: [2, 2, 2, 2],
  },
  {
    id: 'rice',
    name: 'Rice University',
    shortName: 'Rice',
    location: 'Houston, TX',
    type: 'Private Research',
    size: 'Small',
    tier: 'elite',
    difficulty: 'reach',
    category: 'Elite',
    tuition: '$54,960/yr',
    acceptanceRate: '9%',
    enrollment: '8,000',
    topPrograms: ['Engineering', 'Computer Science', 'Architecture', 'Music', 'Business (Jones)'],
    description: 'A small elite university with a residential college system, exceptional engineering, and strong arts programs.',
    strengths: ['STEM', 'Creative'],
    tags: ['Engineering', 'Architecture', 'Small Campus', 'Research'],
    w: [3, 2, 1, 2],
  },
  {
    id: 'georgetown',
    name: 'Georgetown University',
    shortName: 'Georgetown',
    location: 'Washington, D.C.',
    type: 'Private Research',
    size: 'Large',
    tier: 'elite',
    difficulty: 'reach',
    category: 'Elite',
    tuition: '$62,796/yr',
    acceptanceRate: '12%',
    enrollment: '20,000',
    topPrograms: ['International Relations', 'Political Science', 'Business (McDonough)', 'Law', 'Pre-Med'],
    description: 'The top school for international relations and government — located steps from the US Capitol.',
    strengths: ['Social', 'Business'],
    tags: ['International Relations', 'Government', 'Business', 'DC'],
    w: [1, 1, 3, 3],
  },
  {
    id: 'usc',
    name: 'University of Southern California',
    shortName: 'USC',
    location: 'Los Angeles, CA',
    type: 'Private Research',
    size: 'Large',
    tier: 'elite',
    difficulty: 'target',
    category: 'Elite',
    tuition: '$65,237/yr',
    acceptanceRate: '13%',
    enrollment: '48,000',
    topPrograms: ['Film Production', 'Business (Marshall)', 'Engineering', 'Communications', 'Architecture'],
    description: 'The entertainment capital of the world — USC dominates film, media, and communications alongside strong business and engineering.',
    strengths: ['Creative', 'Business', 'STEM'],
    tags: ['Film', 'Media', 'Business', 'LA', 'Entertainment'],
    w: [2, 3, 2, 3],
  },
  {
    id: 'nyu',
    name: 'New York University',
    shortName: 'NYU',
    location: 'New York, NY',
    type: 'Private Research',
    size: 'Large',
    tier: 'elite',
    difficulty: 'target',
    category: 'Elite',
    tuition: '$58,168/yr',
    acceptanceRate: '13%',
    enrollment: '60,000',
    topPrograms: ['Film (Tisch)', 'Business (Stern)', 'Computer Science', 'Psychology', 'Nursing'],
    description: 'New York City is your campus — NYU excels in film, business, arts, and social sciences in the heart of Manhattan.',
    strengths: ['Creative', 'Business', 'Social'],
    tags: ['NYC', 'Film', 'Arts', 'Business', 'Diverse'],
    w: [1, 3, 2, 3],
  },
  {
    id: 'carnegie-mellon',
    name: 'Carnegie Mellon University',
    shortName: 'CMU',
    location: 'Pittsburgh, PA',
    type: 'Private Research',
    size: 'Medium',
    tier: 'elite',
    difficulty: 'reach',
    category: 'Elite',
    tuition: '$58,924/yr',
    acceptanceRate: '15%',
    enrollment: '15,800',
    topPrograms: ['Computer Science', 'Robotics', 'Design', 'Business (Tepper)', 'Drama'],
    description: 'The #1 CS program in the world — also home to elite design, drama, and robotics programs.',
    strengths: ['STEM', 'Creative'],
    tags: ['STEM', 'Tech', 'Design', 'CS #1'],
    w: [3, 2, 0, 1],
  },
  {
    id: 'umich',
    name: 'University of Michigan',
    shortName: 'U of Michigan',
    location: 'Ann Arbor, MI',
    type: 'Public Research',
    size: 'Large',
    tier: 'public',
    difficulty: 'target',
    category: 'Public',
    tuition: '$15,948/yr (in-state)',
    acceptanceRate: '20%',
    enrollment: '47,000',
    topPrograms: ['Engineering', 'Business (Ross)', 'Pre-Med', 'Political Science', 'Computer Science'],
    description: 'A flagship public university with elite programs across nearly every discipline and a legendary campus culture.',
    strengths: ['STEM', 'Business', 'Social'],
    tags: ['Public', 'Research', 'Diverse', 'Big Ten'],
    w: [3, 1, 2, 3],
  },
  {
    id: 'uw-seattle',
    name: 'University of Washington',
    shortName: 'UW Seattle',
    location: 'Seattle, WA',
    type: 'Public Research',
    size: 'Large',
    tier: 'public',
    difficulty: 'target',
    category: 'Public',
    tuition: '$11,839/yr (in-state)',
    acceptanceRate: '49%',
    enrollment: '52,000',
    topPrograms: ['Computer Science', 'Engineering', 'Medicine', 'Business', 'Environmental Science'],
    description: 'A top public research university in the heart of the Pacific Northwest tech corridor — Amazon and Microsoft are neighbors.',
    strengths: ['STEM', 'Business'],
    tags: ['Public', 'Tech', 'Research', 'Pacific Northwest'],
    w: [3, 1, 1, 2],
  },
  {
    id: 'unc',
    name: 'UNC Chapel Hill',
    shortName: 'UNC',
    location: 'Chapel Hill, NC',
    type: 'Public Research',
    size: 'Large',
    tier: 'public',
    difficulty: 'target',
    category: 'Public',
    tuition: '$9,018/yr (in-state)',
    acceptanceRate: '19%',
    enrollment: '32,000',
    topPrograms: ['Journalism', 'Public Health', 'Business (Kenan-Flagler)', 'Pre-Med', 'Political Science'],
    description: 'One of the best public universities in the South — exceptional journalism, public health, and business programs.',
    strengths: ['Social', 'Business', 'Creative'],
    tags: ['Public', 'Journalism', 'Public Health', 'Value'],
    w: [1, 2, 3, 2],
  },
  {
    id: 'boston-university',
    name: 'Boston University',
    shortName: 'BU',
    location: 'Boston, MA',
    type: 'Private Research',
    size: 'Large',
    tier: 'elite',
    difficulty: 'target',
    category: 'Elite',
    tuition: '$62,360/yr',
    acceptanceRate: '19%',
    enrollment: '36,000',
    topPrograms: ['Communications', 'Business (Questrom)', 'Engineering', 'Pre-Med', 'Film & TV'],
    description: 'A large urban research university in Boston with strong programs in communications, business, and pre-med.',
    strengths: ['Creative', 'Business', 'STEM'],
    tags: ['Boston', 'Communications', 'Business', 'Urban'],
    w: [2, 2, 2, 2],
  },
  {
    id: 'tufts',
    name: 'Tufts University',
    shortName: 'Tufts',
    location: 'Medford, MA',
    type: 'Private Research',
    size: 'Medium',
    tier: 'elite',
    difficulty: 'target',
    category: 'Elite',
    tuition: '$65,222/yr',
    acceptanceRate: '11%',
    enrollment: '12,000',
    topPrograms: ['International Relations', 'Engineering', 'Pre-Med', 'Computer Science', 'Psychology'],
    description: 'Known for international relations, civic engagement, and a strong pre-med track in a collaborative environment.',
    strengths: ['Social', 'STEM'],
    tags: ['International Relations', 'Civic', 'Research', 'Pre-Med'],
    w: [2, 1, 3, 1],
  },
  {
    id: 'emory',
    name: 'Emory University',
    shortName: 'Emory',
    location: 'Atlanta, GA',
    type: 'Private Research',
    size: 'Large',
    tier: 'elite',
    difficulty: 'target',
    category: 'Elite',
    tuition: '$57,948/yr',
    acceptanceRate: '11%',
    enrollment: '15,000',
    topPrograms: ['Pre-Med', 'Public Health', 'Business (Goizueta)', 'Psychology', 'Computer Science'],
    description: 'A top research university with exceptional pre-med, public health, and business programs in Atlanta.',
    strengths: ['STEM', 'Social', 'Business'],
    tags: ['Pre-Med', 'Public Health', 'Business', 'Research'],
    w: [2, 1, 2, 2],
  },

  // ── UC System ────────────────────────────────────────────────────────────────
  {
    id: 'uc-berkeley',
    name: 'UC Berkeley',
    shortName: 'UC Berkeley',
    location: 'Berkeley, CA',
    type: 'Public Research',
    size: 'Large',
    tier: 'uc',
    difficulty: 'reach',
    category: 'UC',
    tuition: '$14,312/yr (in-state)',
    acceptanceRate: '14%',
    enrollment: '45,000',
    topPrograms: ['EECS', 'Data Science', 'Business (Haas)', 'Environmental Science', 'Political Science'],
    description: 'The #1 public university in the world — world-class research, diverse community, and unbeatable value.',
    strengths: ['STEM', 'Business', 'Social'],
    tags: ['Public', 'STEM', 'Diverse', 'Research'],
    w: [3, 1, 2, 2],
  },
  {
    id: 'ucla',
    name: 'UCLA',
    shortName: 'UCLA',
    location: 'Los Angeles, CA',
    type: 'Public Research',
    size: 'Large',
    tier: 'uc',
    difficulty: 'reach',
    category: 'UC',
    tuition: '$13,804/yr (in-state)',
    acceptanceRate: '9%',
    enrollment: '47,000',
    topPrograms: ['Film & TV', 'Engineering', 'Business (Anderson)', 'Pre-Med', 'Psychology'],
    description: 'A top-10 public university in the entertainment capital — exceptional film, engineering, and pre-med programs.',
    strengths: ['Creative', 'STEM', 'Social'],
    tags: ['Public', 'Film', 'Research', 'LA'],
    w: [2, 3, 2, 2],
  },
  {
    id: 'ucsd',
    name: 'UC San Diego',
    shortName: 'UCSD',
    location: 'La Jolla, CA',
    type: 'Public Research',
    size: 'Large',
    tier: 'uc',
    difficulty: 'target',
    category: 'UC',
    tuition: '$13,752/yr (in-state)',
    acceptanceRate: '24%',
    enrollment: '42,000',
    topPrograms: ['Biology', 'Computer Science', 'Cognitive Science', 'Engineering', 'Data Science'],
    description: 'A leading research university with exceptional programs in science, engineering, and cognitive science.',
    strengths: ['STEM'],
    tags: ['Public', 'Research', 'STEM', 'Science'],
    w: [3, 0, 1, 1],
  },
  {
    id: 'uci',
    name: 'UC Irvine',
    shortName: 'UCI',
    location: 'Irvine, CA',
    type: 'Public Research',
    size: 'Large',
    tier: 'uc',
    difficulty: 'target',
    category: 'UC',
    tuition: '$13,738/yr (in-state)',
    acceptanceRate: '27%',
    enrollment: '37,000',
    topPrograms: ['Computer Science', 'Business', 'Biology', 'Criminology', 'Engineering'],
    description: 'A rising UC campus with strong CS, business, and criminology programs in sunny Orange County.',
    strengths: ['STEM', 'Business', 'Social'],
    tags: ['Public', 'CS', 'Business', 'Criminology'],
    w: [3, 1, 2, 2],
  },
  {
    id: 'ucsb',
    name: 'UC Santa Barbara',
    shortName: 'UCSB',
    location: 'Santa Barbara, CA',
    type: 'Public Research',
    size: 'Large',
    tier: 'uc',
    difficulty: 'target',
    category: 'UC',
    tuition: '$14,312/yr (in-state)',
    acceptanceRate: '30%',
    enrollment: '26,000',
    topPrograms: ['Environmental Science', 'Physics', 'Computer Science', 'Economics', 'Film & Media Studies'],
    description: 'A beautiful beachside research university with Nobel laureates on faculty and strong STEM and arts programs.',
    strengths: ['STEM', 'Creative'],
    tags: ['Public', 'Research', 'Environmental', 'Beach Campus'],
    w: [3, 2, 1, 1],
  },
  {
    id: 'ucdavis',
    name: 'UC Davis',
    shortName: 'UC Davis',
    location: 'Davis, CA',
    type: 'Public Research',
    size: 'Large',
    tier: 'uc',
    difficulty: 'target',
    category: 'UC',
    tuition: '$14,419/yr (in-state)',
    acceptanceRate: '39%',
    enrollment: '40,000',
    topPrograms: ['Agriculture', 'Veterinary Medicine', 'Environmental Science', 'Biology', 'Engineering'],
    description: 'The top university in the world for agriculture and veterinary medicine — also strong in environmental science.',
    strengths: ['STEM', 'Social'],
    tags: ['Public', 'Agriculture', 'Veterinary', 'Environmental'],
    w: [3, 1, 2, 1],
  },
  {
    id: 'ucsc',
    name: 'UC Santa Cruz',
    shortName: 'UCSC',
    location: 'Santa Cruz, CA',
    type: 'Public Research',
    size: 'Large',
    tier: 'uc',
    difficulty: 'safety',
    category: 'UC',
    tuition: '$14,020/yr (in-state)',
    acceptanceRate: '47%',
    enrollment: '19,000',
    topPrograms: ['Computer Science', 'Game Design', 'Environmental Studies', 'Film & Digital Media', 'Psychology'],
    description: 'A creative and progressive UC campus known for game design, digital media, and environmental studies.',
    strengths: ['Creative', 'STEM', 'Social'],
    tags: ['Public', 'Game Design', 'Creative', 'Environmental'],
    w: [2, 3, 2, 1],
  },
  {
    id: 'ucr',
    name: 'UC Riverside',
    shortName: 'UCR',
    location: 'Riverside, CA',
    type: 'Public Research',
    size: 'Large',
    tier: 'uc',
    difficulty: 'safety',
    category: 'UC',
    tuition: '$13,827/yr (in-state)',
    acceptanceRate: '66%',
    enrollment: '26,000',
    topPrograms: ['Biology', 'Business', 'Engineering', 'Public Policy', 'Environmental Science'],
    description: 'A diverse and accessible UC campus with strong biology, business, and public policy programs.',
    strengths: ['STEM', 'Business', 'Social'],
    tags: ['Public', 'Diverse', 'Accessible', 'Biology'],
    w: [2, 1, 2, 2],
  },
  {
    id: 'ucmerced',
    name: 'UC Merced',
    shortName: 'UC Merced',
    location: 'Merced, CA',
    type: 'Public Research',
    size: 'Medium',
    tier: 'uc',
    difficulty: 'safety',
    category: 'UC',
    tuition: '$13,432/yr (in-state)',
    acceptanceRate: '78%',
    enrollment: '9,000',
    topPrograms: ['Engineering', 'Environmental Engineering', 'Computer Science', 'Biology', 'Management'],
    description: 'The newest UC campus — small, growing, and focused on sustainability, engineering, and research.',
    strengths: ['STEM'],
    tags: ['Public', 'Newest UC', 'Sustainability', 'Engineering'],
    w: [3, 1, 1, 1],
  },

  // ── Safety / Match Schools ────────────────────────────────────────────────
  {
    id: 'sjsu',
    name: 'San Jose State University',
    shortName: 'SJSU',
    location: 'San Jose, CA',
    type: 'Public',
    size: 'Large',
    tier: 'safety',
    difficulty: 'safety',
    category: 'Safety',
    tuition: '$7,852/yr (in-state)',
    acceptanceRate: '67%',
    enrollment: '36,000',
    topPrograms: ['Computer Science', 'Engineering', 'Business', 'Nursing', 'Animation'],
    description: 'Located in the heart of Silicon Valley — SJSU grads are hired by every major tech company.',
    strengths: ['STEM', 'Business', 'Creative'],
    tags: ['Public', 'Silicon Valley', 'CS', 'Affordable'],
    w: [3, 2, 1, 2],
  },
  {
    id: 'csu-fullerton',
    name: 'Cal State Fullerton',
    shortName: 'CSUF',
    location: 'Fullerton, CA',
    type: 'Public',
    size: 'Large',
    tier: 'safety',
    difficulty: 'safety',
    category: 'Safety',
    tuition: '$6,884/yr (in-state)',
    acceptanceRate: '67%',
    enrollment: '41,000',
    topPrograms: ['Business', 'Communications', 'Computer Science', 'Education', 'Fine Arts'],
    description: 'One of the largest CSU campuses with strong business, communications, and arts programs in Southern California.',
    strengths: ['Business', 'Creative', 'Social'],
    tags: ['Public', 'Business', 'Communications', 'Affordable'],
    w: [1, 2, 2, 3],
  },
  {
    id: 'asu',
    name: 'Arizona State University',
    shortName: 'ASU',
    location: 'Tempe, AZ',
    type: 'Public Research',
    size: 'Large',
    tier: 'safety',
    difficulty: 'safety',
    category: 'Safety',
    tuition: '$11,338/yr (in-state)',
    acceptanceRate: '88%',
    enrollment: '83,000',
    topPrograms: ['Business (W.P. Carey)', 'Engineering', 'Journalism', 'Sustainability', 'Computer Science'],
    description: 'The most innovative university in the US — massive, accessible, and with top-ranked business and journalism programs.',
    strengths: ['Business', 'STEM', 'Creative'],
    tags: ['Public', 'Innovative', 'Business', 'Accessible'],
    w: [2, 2, 1, 3],
  },
  {
    id: 'georgia-tech',
    name: 'Georgia Tech',
    shortName: 'Georgia Tech',
    location: 'Atlanta, GA',
    type: 'Public Research',
    size: 'Large',
    tier: 'public',
    difficulty: 'target',
    category: 'Public',
    tuition: '$12,682/yr (in-state)',
    acceptanceRate: '21%',
    enrollment: '44,000',
    topPrograms: ['Engineering', 'Computer Science', 'Business (Scheller)', 'Architecture', 'Industrial Design'],
    description: 'A top-ranked public tech university offering world-class engineering and computing programs at great value.',
    strengths: ['STEM', 'Creative'],
    tags: ['Public', 'STEM', 'Engineering', 'Value'],
    w: [3, 1, 0, 1],
  },
];

// ─── Fit scoring ──────────────────────────────────────────────────────────────
// Computes a 0-100 fit score for a college given the user's bucket scores.

export function computeCollegeFit(
  college: College,
  scores: { stem: number; creative: number; social: number; business: number },
  total: number,
): number {
  const raw =
    college.w[0] * scores.stem +
    college.w[1] * scores.creative +
    college.w[2] * scores.social +
    college.w[3] * scores.business;
  const maxPossible = Math.max(...college.w) * (total || 1);
  const base = maxPossible > 0 ? Math.round((raw / maxPossible) * 100) : 50;
  return Math.min(99, Math.max(38, base));
}
