// ─── Majors Master Data ───────────────────────────────────────────────────────
// Grouped into clusters that map directly to the 4 profile buckets.

export type MajorCluster = 'STEM' | 'Business' | 'Creative' | 'Social' | 'Healthcare' | 'Law' | 'Interdisciplinary';

export interface Major {
  id: string;
  name: string;
  cluster: MajorCluster;
  description: string;
  careers: string[];           // sample career paths
  avgSalary: string;
  // Bucket affinities [stem, creative, social, business]
  w: [number, number, number, number];
}

export const majors: Major[] = [

  // ── STEM ─────────────────────────────────────────────────────────────────────
  { id: 'cs',              name: 'Computer Science',                cluster: 'STEM',             description: 'Algorithms, software systems, AI, and the theory behind computing.',                     careers: ['Software Engineer', 'AI Engineer', 'Data Scientist', 'Product Manager'],          avgSalary: '$110k+', w: [3, 1, 0, 1] },
  { id: 'software-eng',   name: 'Software Engineering',            cluster: 'STEM',             description: 'Applied CS focused on building reliable, scalable software systems.',                    careers: ['Software Engineer', 'Systems Engineer', 'DevOps Engineer'],                       avgSalary: '$110k+', w: [3, 1, 0, 1] },
  { id: 'data-science',   name: 'Data Science',                    cluster: 'STEM',             description: 'Statistics, machine learning, and data analysis to extract insights from data.',         careers: ['Data Scientist', 'Data Analyst', 'ML Engineer', 'Business Analyst'],              avgSalary: '$105k+', w: [3, 0, 0, 2] },
  { id: 'it',             name: 'Information Technology',          cluster: 'STEM',             description: 'Managing and supporting technology infrastructure and systems.',                          careers: ['IT Specialist', 'Systems Admin', 'Network Engineer'],                             avgSalary: '$75k+',  w: [2, 0, 1, 1] },
  { id: 'cybersecurity',  name: 'Cybersecurity',                   cluster: 'STEM',             description: 'Protecting digital systems, networks, and data from cyber threats.',                     careers: ['Cybersecurity Analyst', 'Penetration Tester', 'Security Engineer'],               avgSalary: '$95k+',  w: [3, 0, 0, 1] },
  { id: 'ai-ml',          name: 'Artificial Intelligence / ML',    cluster: 'STEM',             description: 'Building intelligent systems — neural networks, NLP, computer vision, and robotics.',    careers: ['AI Engineer', 'ML Engineer', 'Research Scientist', 'Data Scientist'],             avgSalary: '$130k+', w: [3, 1, 0, 1] },
  { id: 'ee',             name: 'Electrical Engineering',          cluster: 'STEM',             description: 'Circuits, electronics, power systems, and signal processing.',                           careers: ['Electrical Engineer', 'Robotics Engineer', 'Systems Engineer'],                   avgSalary: '$90k+',  w: [3, 1, 0, 0] },
  { id: 'me',             name: 'Mechanical Engineering',          cluster: 'STEM',             description: 'Design and build mechanical systems — engines, machines, and manufacturing.',            careers: ['Mechanical Engineer', 'Aerospace Engineer', 'Robotics Engineer'],                 avgSalary: '$88k+',  w: [3, 1, 0, 0] },
  { id: 'ce',             name: 'Civil Engineering',               cluster: 'STEM',             description: 'Design infrastructure — bridges, roads, buildings, and water systems.',                  careers: ['Civil Engineer', 'Structural Engineer', 'Urban Planner'],                         avgSalary: '$82k+',  w: [3, 1, 1, 0] },
  { id: 'chem-eng',       name: 'Chemical Engineering',            cluster: 'STEM',             description: 'Apply chemistry to design industrial processes for chemicals, fuels, and pharma.',       careers: ['Chemical Engineer', 'Process Engineer', 'Materials Scientist'],                   avgSalary: '$95k+',  w: [3, 0, 0, 1] },
  { id: 'bme',            name: 'Biomedical Engineering',          cluster: 'STEM',             description: 'Develop medical devices, prosthetics, and diagnostic equipment.',                        careers: ['Biomedical Engineer', 'Medical Device Designer', 'Research Scientist'],           avgSalary: '$90k+',  w: [3, 1, 1, 0] },
  { id: 'aero-eng',       name: 'Aerospace Engineering',           cluster: 'STEM',             description: 'Design aircraft, spacecraft, and propulsion systems.',                                   careers: ['Aerospace Engineer', 'Systems Engineer', 'Defense Contractor'],                   avgSalary: '$100k+', w: [3, 1, 0, 0] },
  { id: 'biology',        name: 'Biology',                         cluster: 'STEM',             description: 'Study living organisms — from cells and genetics to ecosystems.',                        careers: ['Biologist', 'Research Scientist', 'Pre-Med', 'Environmental Scientist'],          avgSalary: '$65k+',  w: [3, 0, 1, 0] },
  { id: 'biochem',        name: 'Biochemistry',                    cluster: 'STEM',             description: 'The chemistry of life — proteins, DNA, metabolism, and drug development.',              careers: ['Biochemist', 'Pharmacist', 'Research Scientist', 'Pre-Med'],                      avgSalary: '$75k+',  w: [3, 0, 0, 0] },
  { id: 'physics',        name: 'Physics',                         cluster: 'STEM',             description: 'Explore the fundamental laws governing matter, energy, and the universe.',               careers: ['Physicist', 'Research Scientist', 'Engineer', 'Data Scientist'],                  avgSalary: '$90k+',  w: [3, 0, 0, 0] },
  { id: 'math',           name: 'Mathematics',                     cluster: 'STEM',             description: 'Pure and applied math — the language of science, engineering, and finance.',            careers: ['Mathematician', 'Actuary', 'Data Scientist', 'Financial Analyst'],                avgSalary: '$95k+',  w: [3, 0, 0, 2] },
  { id: 'stats',          name: 'Statistics',                      cluster: 'STEM',             description: 'Collect, analyze, and interpret data to make evidence-based decisions.',                 careers: ['Statistician', 'Data Scientist', 'Actuary', 'Research Analyst'],                  avgSalary: '$95k+',  w: [3, 0, 0, 2] },
  { id: 'env-sci',        name: 'Environmental Science',           cluster: 'STEM',             description: 'Study environmental systems and develop solutions to ecological challenges.',             careers: ['Environmental Scientist', 'Environmental Engineer', 'Policy Analyst'],            avgSalary: '$65k+',  w: [3, 1, 2, 0] },

  // ── Business ─────────────────────────────────────────────────────────────────
  { id: 'biz-admin',      name: 'Business Administration',         cluster: 'Business',         description: 'Broad foundation in management, operations, finance, and strategy.',                     careers: ['Business Analyst', 'Manager', 'Entrepreneur', 'Consultant'],                      avgSalary: '$70k+',  w: [1, 1, 1, 3] },
  { id: 'finance',        name: 'Finance',                         cluster: 'Business',         description: 'Financial markets, investment analysis, corporate finance, and wealth management.',      careers: ['Financial Analyst', 'Investment Banker', 'CFO', 'Actuary'],                       avgSalary: '$85k+',  w: [2, 0, 0, 3] },
  { id: 'accounting',     name: 'Accounting',                      cluster: 'Business',         description: 'Financial reporting, auditing, taxation, and compliance.',                               careers: ['Accountant', 'CPA', 'Auditor', 'Financial Controller'],                           avgSalary: '$70k+',  w: [2, 0, 1, 2] },
  { id: 'marketing',      name: 'Marketing',                       cluster: 'Business',         description: 'Brand strategy, consumer behavior, digital marketing, and advertising.',                 careers: ['Marketing Manager', 'Brand Manager', 'Digital Marketer', 'CMO'],                  avgSalary: '$70k+',  w: [0, 2, 2, 3] },
  { id: 'economics',      name: 'Economics',                       cluster: 'Business',         description: 'How markets, governments, and individuals allocate scarce resources.',                   careers: ['Economist', 'Policy Analyst', 'Financial Analyst', 'Consultant'],                 avgSalary: '$80k+',  w: [3, 0, 1, 2] },
  { id: 'entrepreneurship', name: 'Entrepreneurship',              cluster: 'Business',         description: 'Launch and grow ventures — business model design, fundraising, and scaling.',           careers: ['Entrepreneur', 'Startup Founder', 'Product Manager', 'VC Analyst'],               avgSalary: 'Varies', w: [1, 2, 1, 3] },
  { id: 'intl-business',  name: 'International Business',          cluster: 'Business',         description: 'Global trade, cross-cultural management, and international markets.',                    careers: ['International Business Manager', 'Diplomat', 'Trade Analyst'],                    avgSalary: '$75k+',  w: [1, 1, 2, 3] },
  { id: 'management',     name: 'Management',                      cluster: 'Business',         description: 'Organizational behavior, leadership, HR, and operations management.',                    careers: ['Manager', 'HR Manager', 'Operations Director', 'Consultant'],                     avgSalary: '$70k+',  w: [0, 1, 2, 3] },
  { id: 'supply-chain-m', name: 'Supply Chain Management',         cluster: 'Business',         description: 'Logistics, procurement, operations, and global supply chain optimization.',              careers: ['Supply Chain Manager', 'Logistics Analyst', 'Operations Manager'],                avgSalary: '$75k+',  w: [2, 0, 1, 3] },
  { id: 'real-estate-m',  name: 'Real Estate',                     cluster: 'Business',         description: 'Property markets, investment analysis, development, and property management.',          careers: ['Real Estate Agent', 'Property Developer', 'Real Estate Analyst'],                 avgSalary: '$70k+',  w: [1, 1, 1, 3] },
  { id: 'biz-analytics',  name: 'Business Analytics',              cluster: 'Business',         description: 'Data-driven decision making — combining business strategy with quantitative analysis.',  careers: ['Business Analyst', 'Data Analyst', 'Product Manager', 'Consultant'],              avgSalary: '$85k+',  w: [2, 1, 1, 3] },

  // ── Creative / Arts / Media ───────────────────────────────────────────────────
  { id: 'graphic-design', name: 'Graphic Design',                  cluster: 'Creative',         description: 'Visual communication — typography, branding, print, and digital design.',               careers: ['Graphic Designer', 'Brand Designer', 'Art Director'],                             avgSalary: '$55k+',  w: [0, 3, 1, 1] },
  { id: 'product-design', name: 'Product Design',                  cluster: 'Creative',         description: 'Design physical and digital products that are functional, beautiful, and usable.',      careers: ['Product Designer', 'Industrial Designer', 'UX Designer'],                         avgSalary: '$90k+',  w: [2, 3, 1, 1] },
  { id: 'ux-design',      name: 'UX / UI Design',                  cluster: 'Creative',         description: 'Human-centered design of digital interfaces and user experiences.',                      careers: ['UX Designer', 'UI Designer', 'Product Designer', 'UX Researcher'],                avgSalary: '$90k+',  w: [1, 3, 2, 1] },
  { id: 'architecture',   name: 'Architecture',                    cluster: 'Creative',         description: 'Design buildings and spaces that shape how people live, work, and experience the world.', careers: ['Architect', 'Urban Designer', 'Interior Designer'],                             avgSalary: '$80k+',  w: [2, 3, 1, 1] },
  { id: 'film',           name: 'Film Production',                 cluster: 'Creative',         description: 'Storytelling through cinema — directing, cinematography, editing, and production.',      careers: ['Film Director', 'Video Editor', 'Cinematographer', 'Producer'],                   avgSalary: '$60k+',  w: [0, 3, 2, 1] },
  { id: 'digital-media',  name: 'Digital Media',                   cluster: 'Creative',         description: 'Create content for digital platforms — video, social, interactive, and web.',           careers: ['Content Creator', 'Social Media Manager', 'Digital Producer'],                   avgSalary: '$55k+',  w: [1, 3, 2, 1] },
  { id: 'animation',      name: 'Animation',                       cluster: 'Creative',         description: '2D and 3D animation for film, TV, games, and advertising.',                             careers: ['Animator', 'Motion Designer', 'VFX Artist', 'Game Artist'],                       avgSalary: '$65k+',  w: [1, 3, 1, 0] },
  { id: 'game-design',    name: 'Game Design',                     cluster: 'Creative',         description: 'Design game mechanics, levels, and experiences — combining art, code, and storytelling.', careers: ['Game Designer', 'Game Developer', 'Level Designer'],                           avgSalary: '$70k+',  w: [2, 3, 1, 1] },
  { id: 'photography',    name: 'Photography',                     cluster: 'Creative',         description: 'Visual storytelling through the lens — editorial, commercial, and fine art photography.', careers: ['Photographer', 'Photo Editor', 'Art Director'],                               avgSalary: '$50k+',  w: [0, 3, 1, 1] },
  { id: 'music',          name: 'Music',                           cluster: 'Creative',         description: 'Performance, composition, music theory, and music production.',                          careers: ['Music Producer', 'Musician', 'Music Teacher', 'Sound Designer'],                  avgSalary: '$50k+',  w: [0, 3, 1, 0] },
  { id: 'fine-arts',      name: 'Fine Arts',                       cluster: 'Creative',         description: 'Painting, sculpture, printmaking, and visual art — developing a personal artistic voice.', careers: ['Artist', 'Art Director', 'Art Teacher', 'Gallery Curator'],                  avgSalary: '$45k+',  w: [0, 3, 1, 0] },
  { id: 'creative-writing', name: 'Creative Writing',              cluster: 'Creative',         description: 'Fiction, poetry, screenwriting, and narrative nonfiction.',                              careers: ['Author', 'Screenwriter', 'Copywriter', 'Editor'],                                 avgSalary: '$50k+',  w: [0, 3, 2, 1] },
  { id: 'journalism',     name: 'Journalism',                      cluster: 'Creative',         description: 'Reporting, investigating, and communicating news across print, digital, and broadcast.',  careers: ['Journalist', 'Reporter', 'Editor', 'Broadcast Journalist'],                       avgSalary: '$55k+',  w: [0, 2, 3, 1] },
  { id: 'communications', name: 'Communications',                  cluster: 'Creative',         description: 'Strategic communication, public relations, media, and organizational messaging.',        careers: ['PR Specialist', 'Communications Manager', 'Content Strategist'],                 avgSalary: '$60k+',  w: [0, 2, 3, 2] },

  // ── Social Sciences ───────────────────────────────────────────────────────────
  { id: 'psychology',     name: 'Psychology',                      cluster: 'Social',           description: 'Human behavior, cognition, emotion, and mental health.',                                 careers: ['Psychologist', 'Therapist', 'HR Manager', 'UX Researcher'],                       avgSalary: '$60k+',  w: [1, 1, 3, 0] },
  { id: 'sociology',      name: 'Sociology',                       cluster: 'Social',           description: 'Social structures, institutions, inequality, and collective behavior.',                  careers: ['Social Worker', 'Policy Analyst', 'Nonprofit Director', 'HR Manager'],            avgSalary: '$55k+',  w: [0, 1, 3, 0] },
  { id: 'political-sci',  name: 'Political Science',               cluster: 'Social',           description: 'Government, political theory, international relations, and public policy.',              careers: ['Political Scientist', 'Diplomat', 'Policy Analyst', 'Lawyer'],                    avgSalary: '$65k+',  w: [1, 1, 3, 1] },
  { id: 'anthropology',   name: 'Anthropology',                    cluster: 'Social',           description: 'Human cultures, societies, evolution, and cross-cultural understanding.',                careers: ['Anthropologist', 'Cultural Consultant', 'Nonprofit Director'],                    avgSalary: '$55k+',  w: [0, 1, 3, 0] },
  { id: 'education',      name: 'Education',                       cluster: 'Social',           description: 'Teaching, curriculum design, educational psychology, and school leadership.',            careers: ['Teacher', 'School Counselor', 'Principal', 'Instructional Designer'],             avgSalary: '$55k+',  w: [0, 1, 3, 0] },
  { id: 'history',        name: 'History',                         cluster: 'Social',           description: 'Analyze the past to understand the present — research, writing, and critical thinking.', careers: ['Historian', 'Teacher', 'Lawyer', 'Policy Analyst'],                             avgSalary: '$55k+',  w: [0, 1, 3, 1] },
  { id: 'criminology',    name: 'Criminology',                     cluster: 'Social',           description: 'The study of crime, criminal behavior, and the justice system.',                        careers: ['Criminal Justice Officer', 'Criminologist', 'Policy Analyst', 'Social Worker'],   avgSalary: '$55k+',  w: [1, 0, 3, 1] },
  { id: 'intl-relations', name: 'International Relations',         cluster: 'Social',           description: 'Global politics, diplomacy, international law, and foreign policy.',                    careers: ['Diplomat', 'Foreign Service Officer', 'Policy Analyst', 'Journalist'],            avgSalary: '$65k+',  w: [1, 1, 3, 1] },
  { id: 'public-policy',  name: 'Public Policy',                   cluster: 'Social',           description: 'Design and evaluate government policies that address social, economic, and health issues.', careers: ['Policy Analyst', 'Government Advisor', 'Nonprofit Director'],                 avgSalary: '$65k+',  w: [1, 0, 3, 1] },
  { id: 'linguistics',    name: 'Linguistics',                     cluster: 'Social',           description: 'The science of language — structure, acquisition, and how language shapes thought.',     careers: ['Linguist', 'Speech Therapist', 'Translator', 'UX Researcher'],                    avgSalary: '$60k+',  w: [1, 2, 2, 0] },

  // ── Healthcare ────────────────────────────────────────────────────────────────
  { id: 'nursing',        name: 'Nursing',                         cluster: 'Healthcare',       description: 'Patient care, clinical skills, and healthcare delivery across all settings.',            careers: ['Nurse (RN)', 'Nurse Practitioner', 'Nurse Educator'],                             avgSalary: '$80k+',  w: [2, 0, 3, 0] },
  { id: 'pre-med',        name: 'Pre-Med / Medicine Track',        cluster: 'Healthcare',       description: 'Preparation for medical school — biology, chemistry, and clinical experience.',         careers: ['Doctor', 'Surgeon', 'Specialist', 'Researcher'],                                  avgSalary: '$200k+', w: [3, 0, 2, 0] },
  { id: 'public-health',  name: 'Public Health',                   cluster: 'Healthcare',       description: 'Protect and improve population health through policy, research, and education.',         careers: ['Public Health Specialist', 'Epidemiologist', 'Health Policy Analyst'],            avgSalary: '$65k+',  w: [2, 0, 3, 1] },
  { id: 'pharmacy',       name: 'Pharmacy',                        cluster: 'Healthcare',       description: 'Medication science, pharmacology, and patient counseling.',                              careers: ['Pharmacist', 'Pharmaceutical Researcher', 'Clinical Pharmacist'],                 avgSalary: '$125k+', w: [3, 0, 2, 0] },
  { id: 'dentistry',      name: 'Dentistry',                       cluster: 'Healthcare',       description: 'Oral health diagnosis, treatment, and preventive care.',                                 careers: ['Dentist', 'Orthodontist', 'Oral Surgeon'],                                         avgSalary: '$175k+', w: [2, 1, 2, 1] },
  { id: 'nutrition',      name: 'Nutrition',                       cluster: 'Healthcare',       description: 'Food science, dietetics, and the role of nutrition in health and disease.',             careers: ['Nutritionist', 'Dietitian', 'Public Health Specialist'],                          avgSalary: '$60k+',  w: [2, 0, 3, 0] },
  { id: 'kinesiology',    name: 'Kinesiology',                     cluster: 'Healthcare',       description: 'Human movement, exercise science, and physical performance.',                           careers: ['Physical Therapist', 'Athletic Trainer', 'Exercise Physiologist'],                avgSalary: '$60k+',  w: [2, 1, 2, 0] },
  { id: 'physical-therapy', name: 'Physical Therapy',              cluster: 'Healthcare',       description: 'Rehabilitation science — restoring movement and function after injury or illness.',      careers: ['Physical Therapist', 'Sports Medicine Specialist', 'Occupational Therapist'],     avgSalary: '$90k+',  w: [2, 1, 3, 0] },

  // ── Law / Government ─────────────────────────────────────────────────────────
  { id: 'pre-law',        name: 'Pre-Law',                         cluster: 'Law',              description: 'Preparation for law school — critical thinking, research, and argumentation.',          careers: ['Lawyer', 'Judge', 'Policy Analyst', 'Paralegal'],                                 avgSalary: '$90k+',  w: [1, 1, 3, 2] },
  { id: 'criminal-justice', name: 'Criminal Justice',              cluster: 'Law',              description: 'The criminal justice system — law enforcement, courts, and corrections.',               careers: ['Criminal Justice Officer', 'Criminologist', 'Paralegal', 'Social Worker'],        avgSalary: '$55k+',  w: [1, 0, 3, 1] },
  { id: 'public-admin',   name: 'Public Administration',           cluster: 'Law',              description: 'Managing government agencies and public programs for the common good.',                  careers: ['Public Administrator', 'Government Advisor', 'Policy Analyst'],                   avgSalary: '$65k+',  w: [1, 0, 3, 2] },

  // ── Interdisciplinary ─────────────────────────────────────────────────────────
  { id: 'data-analytics', name: 'Data Analytics',                  cluster: 'Interdisciplinary', description: 'Applied data analysis combining statistics, visualization, and business intelligence.', careers: ['Data Analyst', 'Business Analyst', 'Product Manager', 'Data Scientist'],         avgSalary: '$80k+',  w: [3, 1, 1, 2] },
  { id: 'biz-cs',         name: 'Business + CS (Dual Path)',        cluster: 'Interdisciplinary', description: 'Combine technical CS skills with business strategy for high-demand hybrid roles.',     careers: ['Product Manager', 'Tech Entrepreneur', 'Data Scientist', 'Consultant'],           avgSalary: '$110k+', w: [3, 1, 1, 3] },
  { id: 'design-tech',    name: 'Design + Technology',             cluster: 'Interdisciplinary', description: 'Blend creative design with technical skills for product and UX roles.',                careers: ['Product Designer', 'UX Engineer', 'Creative Technologist'],                       avgSalary: '$95k+',  w: [2, 3, 1, 1] },
  { id: 'health-info',    name: 'Health Informatics',              cluster: 'Interdisciplinary', description: 'Bridge healthcare and technology — managing health data to improve patient outcomes.',  careers: ['Health Informatics Specialist', 'Data Analyst', 'Healthcare IT Manager'],         avgSalary: '$85k+',  w: [3, 0, 2, 1] },
  { id: 'env-policy',     name: 'Environmental Policy',            cluster: 'Interdisciplinary', description: 'Combine environmental science with policy to address climate and sustainability.',      careers: ['Policy Analyst', 'Sustainability Consultant', 'Environmental Scientist'],         avgSalary: '$65k+',  w: [2, 1, 3, 1] },
  { id: 'cog-sci',        name: 'Cognitive Science',               cluster: 'Interdisciplinary', description: 'Mind, brain, and intelligence — combining psychology, neuroscience, CS, and philosophy.', careers: ['UX Researcher', 'AI Researcher', 'Psychologist', 'Neuroscientist'],           avgSalary: '$75k+',  w: [2, 1, 2, 1] },
];

// ─── Fit scoring ──────────────────────────────────────────────────────────────

export function computeMajorFit(
  major: Major,
  scores: { stem: number; creative: number; social: number; business: number },
  total: number,
): number {
  const raw =
    major.w[0] * scores.stem +
    major.w[1] * scores.creative +
    major.w[2] * scores.social +
    major.w[3] * scores.business;
  const maxPossible = Math.max(...major.w) * (total || 1);
  const base = maxPossible > 0 ? Math.round((raw / maxPossible) * 100) : 50;
  return Math.min(99, Math.max(35, base));
}
